apiVersion: v1
kind: Service
metadata:
  name: deliveggiemongo
  labels:
    app: deliveggiemongo
spec:
  selector:
    app: deliveggiemongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveggiemongo
spec:
  selector:
    matchLabels:
      app: deliveggiemongo
  replicas: 1
  template:
    metadata:
      labels:
        app: deliveggiemongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          name: mongodb
          image: mongo:5.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi